---
# Task file : OpenStack VM creation

# Creating OpenStack server

- name: Creating VM in OpenStack
  os_server:
    validate_certs: False
    api_timeout: 300
    timeout: 600
    state: "{{ vm_state }}"
    auth:
      auth_url: "{{ cloudstack_auth_url }}"
      username: "{{ cloudstack_login }}"
      password: "{{ cloudstack_password }}"
      project_name: "{{ cloudstask_project }}"
    auth_type: v2password
    auto_ip: "{{ vm_auto_ip }}"
    region_name: "{{ vm_region_name }}"
    availability_zone: "{{ vm_availability_zone }}"
    flavor: "{{ vm_flavor }}"
    image: "{{ vm_image }}"
    meta:
      description: "{{ vm_description }}"
    name: "{{ vm_hostname }}"
    security_groups: "{{ vm_security_group }}"
    network: "{{ vm_network }}"
    userdata: "{{ lookup('file', '{{ inventory_dir }}/user_data_vm/user_data.sh') }}"
  register: my_server

- debug:
        var: myserver.server.private_v4


# Waiting for server to boot

- name: Waiting for VM to boot
  sudo: no
  when: my_server|changed
  local_action: wait_for host="{{ my_server.server.networks[vm_network][0] }}" port=22 timeout=300 search_regex=OpenSSH delay=5
